"""empty message

Revision ID: 360807cdf13b
Revises: 502a611aae72
Create Date: 2021-03-01 14:10:02.487511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360807cdf13b'
down_revision = '502a611aae72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_restaurant', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('user_user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'timestamp')
    op.drop_column('user_restaurant', 'timestamp')
    # ### end Alembic commands ###
